### PR TITLE
Fix ConnectionAbort in IE11

### PR DESCRIPTION
**Pull request by jogibear9988**
for example:
 
https://github.com/hoaproject/Websocket/issues/33

### CODE REVIEW

**Comment by jogibear9988** [comment]
Also here: https://tools.ietf.org/html/rfc6455#section-5.5.3

**Comment by bryceg** [comment]
Strange, have you actually been running into this?  I can see that the tunnel should shut down with the exception being thrown on 0xA being received, but we have yet to see this with our IE clients internally.  Our tunnels are almost constantly sending data though, so maybe we dont run into the 'heartbeat' pong frame from IE.

**Comment by bryceg** [comment]
I see why we have not run into this yet, its because we don't use NetWebSocket by default with our environment.  I'll put out a new release with this fix, thanks.

**Comment by jogibear9988** [comment]
Thanks...

For clarification: What's NetWebSocket?

**Comment by bryceg** [comment]
If you are running on a web server with .net such as IIS then you will likely use the the NetWebSocket.cs implementation which uses System.Net.WebSockets to handle the connection.  If that's not available, then it falls back to the OWIN web socket handler methods, which is defined in the OwinWebSocket.cs class that you submitted a fix for.  You can see the implementation for this in WebSocketConnection.RunWebSocket method.

**Pull request merged**
